# Generated by Django 5.0.4 on 2024-06-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image', models.ImageField(upload_to='images/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=300)),
                ('action', models.CharField(choices=[('BLURRED', 'blurred'), ('BINARY', 'binary'), ('NO_FILTER', 'no filter'), ('INVERT', 'invert'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale')], max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
