# Generated by Django 5.0.4 on 2024-06-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('BLURRED', 'blurred'), ('GRAYSCALE', 'grayscale'), ('INVERT', 'invert'), ('NO_FILTER', 'no filter'), ('BINARY', 'binary'), ('COLORIZED', 'colorized')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
