# Generated by Django 5.0.4 on 2024-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_photo_action_alter_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('BINARY', 'binary'), ('SHARPEN', 'sharpen'), ('VIGNETTE', 'vignette'), ('INVERT', 'invert'), ('COLORIZED', 'colorized'), ('HDR', 'hdr'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('COLD', 'cold'), ('SEPIA', 'sepia'), ('SKETCH', 'sketch'), ('STYLIZATION', 'stylization')], max_length=50, null=True),
        ),
    ]
