# Generated by Django 5.0.4 on 2024-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_photo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('VIGNETTE', 'vignette'), ('SHARPEN', 'sharpen'), ('HDR', 'hdr'), ('COLD', 'cold'), ('SKETCH', 'sketch'), ('SEPIA', 'sepia'), ('STYLIZATION', 'stylization'), ('COLORIZED', 'colorized'), ('INVERT', 'invert'), ('GRAYSCALE', 'grayscale'), ('BINARY', 'binary'), ('BLURRED', 'blurred')], max_length=50, null=True),
        ),
    ]
