# Generated by Django 5.0.4 on 2024-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_photo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('VIGNETTE', 'vignette'), ('STYLIZATION', 'stylization'), ('INVERT', 'invert'), ('COLD', 'cold'), ('BINARY', 'binary'), ('SKETCH', 'sketch'), ('SHARPEN', 'sharpen'), ('SEPIA', 'sepia'), ('COLORIZED', 'colorized'), ('HDR', 'hdr'), ('BLURRED', 'blurred'), ('GRAYSCALE', 'grayscale')], max_length=50, null=True),
        ),
    ]
