# Generated by Django 5.0.4 on 2024-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_photo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('COLD', 'cold'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('VIGNETTE', 'vignette'), ('INVERT', 'invert'), ('BINARY', 'binary'), ('HDR', 'hdr'), ('SEPIA', 'sepia'), ('COLORIZED', 'colorized'), ('STYLIZATION', 'stylization'), ('SKETCH', 'sketch'), ('SHARPEN', 'sharpen')], max_length=50, null=True),
        ),
    ]
